name: Build Dogecoin Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev libboost-test-dev libboost-thread-dev software-properties-common

    - name: Install Berkeley DB 4.8
      run: |
        wget http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
        tar -xzvf db-4.8.30.NC.tar.gz
        cd db-4.8.30.NC/build_unix/
        ../dist/configure --prefix=/usr/local --enable-cxx
        make
        sudo make install

    - name: Clone Dogecoin repository
      run: |
        git clone https://github.com/dogecoin/dogecoin.git
        cd dogecoin
        ./autogen.sh
        ./configure --without-gui --disable-tests LDFLAGS="-L/usr/local/lib" CPPFLAGS="-I/usr/local/include"
        make

    - name: Archive build
      uses: actions/upload-artifact@v2
      with:
        name: dogecoin-core
        path: dogecoin/src/dogecoind

